sudo: required

language: minimal

services: docker

env:
    global:
        - APP_ENV=test
        - APP_SECRET=secret

install:
    - travis_retry docker-compose --file docker-compose.yaml --file docker-compose.test.yaml build

jobs:
    include:

        - stage: Test
          env: HTTP_TEST
          before_script:
              - docker-compose --file docker-compose.yaml --file docker-compose.test.yaml up -d web
          script:
              - if [[ $(curl -sS http://localhost:8080/ping 2>&1) == "pong" ]]; then true; else false; fi

        - stage: Test
          env: TESTS
          script:
              - docker-compose --file docker-compose.yaml --file docker-compose.test.yaml run app vendor/bin/phpunit

        - stage: Code Quality
          env: CODING_STANDARDS
          script:
              - docker-compose --file docker-compose.yaml --file docker-compose.test.yaml run app vendor/bin/phpcs -p

        - stage: Code Quality
          env: STATIC_ANALYSIS
          script:
              - APP_ENV=dev docker-compose --file docker-compose.yaml --file docker-compose.test.yaml run app sh -c "bin/console cache:warmup && vendor/bin/phpstan analyse"

stages:
    - Test
    - name: Code Quality
      if: type = pull_request

if: |
    branch = master OR \
    branch =~ /^(?:[0-9]|[1-9][0-9]*)\.(?:[0-9]|[1-9][0-9]*)$/ OR \
    tag IS present OR \
    type = pull_request
