version: '3.4'

services:
    app:
        build:
            context: .
            target: prod
            args:
                revision: ${IMAGE_REVISION:-master}
        environment:
            APP_SECRET:
        image: libero/dummy-api:${IMAGE_TAG:-master}
    web:
        image: nginx:1.15.5-alpine
        volumes:
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public/:/app/public/
        ports:
            - 8080:80
        depends_on:
            - app
