#!/bin/bash
set -e

docker-compose --file docker-compose.yaml up -d web
docker-compose --file docker-compose.yaml exec app bin/console --version
ping=$(curl -sS http://localhost:8080/ping 2>&1)
[[ "$ping" == "pong" ]]
docker-compose --file docker-compose.yaml down
