ping:
    path: /ping
    controller: libero.dummy_api.controller.ping

content_api:
    resource: .
    type: content_api

error:
    path: /error
    controller: Libero\DummyApi\Controller\ErrorController
