parameters:
    env(DEFAULT_LOCALE): 'en'
    env(POSSIBLE_LOCALES): '%env(DEFAULT_LOCALE)%'
    kernel.data_dir: '%kernel.project_dir%/data'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Libero\DummyApi\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'

    libero.dummy_api.controller.ping:
        class: Libero\PingController\PingController
        tags:
            - name: controller.service_arguments

    # Exceptions are already handled by the ApiProblemBundle, but need to be logged.
    libero.dummy_api.exception_logger:
        autoconfigure: false
        class: Symfony\Component\HttpKernel\EventListener\ExceptionListener
        arguments:
            - ''
            - '@logger'
            - '%kernel.debug%'
        tags:
            - name: kernel.event_listener
              event: kernel.exception
              method: logKernelException
            - name: monolog.logger
              channel: request
